### ISSUE TITLE
It seems to have some bugs

### ISSUE THREAD

**Issue by zhr-zhang** [dishangti/ThreeBody#1]
I'm doing researches on the Three-body Problem and developing an application too.
Your application seems to go wrong.
![image](https://user-images.githubusercontent.com/112841696/213701377-fe9efba0-eb3e-4794-87ea-13beafb239c9.png)

**Comment by dishangti** [comment]
Maybe you should reduce the time for calculation, which in fact means the interval of a Riemann Sum.

**Comment by zhr-zhang** [comment]
I found the problem, actually because the initial positions of the celestial objects are the same, resulting in dividing by 0 when calculating gravity. Adding input restrictions may solve this problem.

**Comment by zhr-zhang** [comment]
This is a part  of my code.
![image](https://user-images.githubusercontent.com/112841696/213841233-f69ac7cf-f486-4cf0-a4e7-d784792be852.png)
It might help solve the problem.

**Comment by zhr-zhang** [comment]
Emm.. 我们似乎可以用中文交流。
![image](https://user-images.githubusercontent.com/112841696/213841333-262e8fe4-2d94-40cd-9615-569cf6817217.png)
